### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by karlml** [prolificinteractive/TouchIDBlogPost#1]
Hi,
you project automatically crash at startup.
![skjermbilde 2016-11-12 kl 23 06 40](https://cloud.githubusercontent.com/assets/9771583/20242398/c7797c0c-a92c-11e6-9070-e0af6b75051a.png)

**Comment by ThibaultKlein** [comment]
Hi @karlml,

Thank you for reporting this issue, I'll take a look at it as soon as possible and fix the crash.

**Comment by jorgecasariego** [comment]
Hey @ThibaultKlein I have the same problem!

@karlml  did you found a solution?

**Comment by karlml** [comment]
@ThibaultKlein Hey, no, but I found another project that worked.
https://bitbucket.org/team-devslopes/touch-id-swift-3/src

**Comment by jorgecasariego** [comment]
@karlml I found a solution. Is just a small change. I created a pull request.

**Comment by ThibaultKlein** [comment]
@jorgecasariego thank you for your pull request, I merged it. @karlml let me know if it works for you now.
